// ─── Chemical Database ───
// Định nghĩa các hóa chất có sẵn trong phòng thí nghiệm

export interface Chemical {
  id: string;
  name: string;
  formula: string;
  color: string;
  concentration?: string;
  category: "acid" | "base" | "indicator" | "metal" | "salt" | "gas" | "organic" | "other";
  state: "liquid" | "solid" | "gas" | "aqueous";
  description: string;
  // Khối lượng mol (g/mol)
  molarMass?: number;
  // Là muối cacbonat (tác dụng với axit giải phóng CO₂)
  carbonate?: boolean;
  // Màu sắc gradient cho dung dịch
  liquidColor: string;
  liquidColorEnd?: string;
  // Độc hại / nguy hiểm
  hazardous?: boolean;
  corrosive?: boolean;
  flammable?: boolean;
  toxic?: boolean;
  // Màu sắc cho chất rắn (hạt, tinh thể)
  solidColor?: string;
  solidColorEnd?: string;
  // Kiểu hiển thị chất rắn: "crystal" | "metal" | "powder" | "chunk"
  solidType?: "crystal" | "metal" | "powder" | "chunk";
}

export const chemicals: Chemical[] = [
  // ─── Dummy Biology/Physics Equipments ───
  {
    id: "microscope",
    name: "Kính hiển vi",
    formula: "Kính",
    color: "#6b7280",
    category: "other",
    state: "solid",
    description: "Dụng cụ quan sát tiêu bản",
    solidType: "chunk",
    solidColor: "#6b7280",
    liquidColor: "transparent"
  },
  {
    id: "onion",
    name: "Vảy hành",
    formula: "Hành",
    color: "#ec4899",
    category: "organic",
    state: "solid",
    description: "Biểu bì vảy hành",
    solidType: "chunk",
    solidColor: "#ec4899",
    liquidColor: "transparent"
  },
  {
    id: "lens",
    name: "Thấu kính",
    formula: "Lens",
    color: "#9ca3af",
    category: "other",
    state: "solid",
    description: "Thấu kính hội tụ",
    solidType: "chunk",
    solidColor: "#9ca3af",
    liquidColor: "transparent"
  },
  {
    id: "object",
    name: "Vật sáng",
    formula: "Vật",
    color: "#eab308",
    category: "other",
    state: "solid",
    description: "Vật sáng AB",
    solidType: "chunk",
    solidColor: "#eab308",
    liquidColor: "transparent"
  },
  // ─── Lớp 10 ───
  {
    id: "kmno4",
    name: "Thuốc tím",
    formula: "KMnO₄",
    color: "#8a2be2",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Chất oxi hóa mạnh, màu tím đặc trưng.",
    molarMass: 158.034,
    liquidColor: "rgba(138, 43, 226, 0.95)",
    liquidColorEnd: "rgba(100, 20, 180, 0.9)",
  },
  {
    id: "feso4",
    name: "Sắt(II) Sunfat",
    formula: "FeSO₄",
    color: "#98fb98",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Muối sắt(II), dung dịch màu xanh lục nhạt.",
    molarMass: 151.908,
    liquidColor: "rgba(152, 251, 152, 0.8)",
    liquidColorEnd: "rgba(120, 220, 120, 0.7)",
  },
  {
    id: "bacl2",
    name: "Bari Clorua",
    formula: "BaCl₂",
    color: "#ffffff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch muối không màu.",
    molarMass: 208.23,
    liquidColor: "rgba(255,255,255,0.95)",
    liquidColorEnd: "rgba(240,248,255,0.9)",
  },
  {
    id: "pbno32",
    name: "Chì(II) Nitrat",
    formula: "Pb(NO₃)₂",
    color: "#ffffff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Muối độc, dùng để tạo kết tủa.",
    molarMass: 331.2,
    liquidColor: "rgba(255,255,255,0.95)",
    liquidColorEnd: "rgba(240,248,255,0.9)",
    toxic: true,
  },
  {
    id: "ki",
    name: "Kali Iodua",
    formula: "KI",
    color: "#ffffff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch muối không màu.",
    molarMass: 166.0,
    liquidColor: "rgba(255,255,255,0.95)",
    liquidColorEnd: "rgba(240,248,255,0.9)",
  },
  {
    id: "mg",
    name: "Magie",
    formula: "Mg",
    color: "#c0c0c0",
    category: "metal",
    state: "solid",
    description: "Kim loại kiềm thổ, hoạt động mạnh.",
    molarMass: 24.305,
    liquidColor: "rgba(192,192,192,1)",
    solidColor: "#d3d3d3",
    solidColorEnd: "#a9a9a9",
    solidType: "metal",
  },
  // ─── Acids ───
  {
    id: "hcl",
    name: "Axit Clohidric",
    formula: "HCl",
    color: "#ffffff",
    concentration: "1M",
    category: "acid",
    state: "aqueous",
    description: "Axit mạnh, không màu, ăn mòn",
    molarMass: 36.46,
    liquidColor: "rgba(255,255,255,0.95)",
    liquidColorEnd: "rgba(230,240,255,0.9)",
    corrosive: true,
    hazardous: true,
  },
  {
    id: "h2so4",
    name: "Axit Sunfuric",
    formula: "H₂SO₄",
    color: "#ffffff",
    concentration: "0.5M",
    category: "acid",
    state: "aqueous",
    description: "Axit mạnh, không màu, đặc quánh",
    molarMass: 98.08,
    liquidColor: "rgba(255,255,255,0.95)",
    liquidColorEnd: "rgba(220,235,255,0.9)",
    corrosive: true,
    hazardous: true,
  },
  {
    id: "hno3",
    name: "Axit Nitric",
    formula: "HNO₃",
    color: "#fff8e0",
    concentration: "0.5M",
    category: "acid",
    state: "aqueous",
    description: "Axit mạnh, có màu vàng nhạt",
    molarMass: 63.01,
    liquidColor: "rgba(255,248,224,0.92)",
    liquidColorEnd: "rgba(240,230,200,0.85)",
    corrosive: true,
    hazardous: true,
  },
  {
    id: "ch3cooh",
    name: "Axit Axetic",
    formula: "CH₃COOH",
    color: "#ffffff",
    concentration: "1M",
    category: "acid",
    state: "aqueous",
    description: "Axit yếu, không màu, mùi giấm",
    molarMass: 60.05,
    liquidColor: "rgba(255,255,255,0.95)",
    liquidColorEnd: "rgba(240,248,255,0.9)",
    corrosive: true,
  },

  // ─── Bases ───
  {
    id: "naoh",
    name: "Natri Hidroxit",
    formula: "NaOH",
    color: "#ffffff",
    concentration: "1M",
    category: "base",
    state: "aqueous",
    description: "Bazơ mạnh, không màu, ăn mòn",
    molarMass: 40.0,
    liquidColor: "rgba(255,255,255,0.95)",
    liquidColorEnd: "rgba(230,255,240,0.9)",
    corrosive: true,
    hazardous: true,
  },
  {
    id: "nh3",
    name: "Amoniac",
    formula: "NH₃",
    color: "#ffffff",
    concentration: "0.5M",
    category: "base",
    state: "aqueous",
    description: "Bazơ yếu, không màu, mùi khai",
    molarMass: 17.03,
    liquidColor: "rgba(255,255,255,0.92)",
    liquidColorEnd: "rgba(230,255,250,0.85)",
    toxic: true,
  },
  {
    id: "caoh2",
    name: "Nước Vôi Trong",
    formula: "Ca(OH)₂",
    color: "#ffffff",
    concentration: "0.1M",
    category: "base",
    state: "aqueous",
    description: "Dung dịch canxi hidroxit, không màu, dùng nhận biết CO₂",
    molarMass: 74.09,
    liquidColor: "rgba(255,255,255,0.95)",
    liquidColorEnd: "rgba(235,248,255,0.9)",
    corrosive: true,
  },

  // ─── Indicators ───
  {
    id: "phenolphthalein",
    name: "Phenolphthalein",
    formula: "C₂₀H₁₄O₄",
    color: "#ffffff",
    concentration: "1%",
    category: "indicator",
    state: "aqueous",
    description: "Chất chỉ thị màu, không màu trong axit, hồng trong bazơ",
    molarMass: 318.32,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,240,255,0.85)",
  },
  {
    id: "quytim",
    name: "Giấy Quỳ Tím",
    formula: "-",
    color: "#8855aa",
    category: "indicator",
    state: "solid",
    description: "Chất chỉ thị màu: đỏ trong axit, xanh trong bazơ",
    liquidColor: "rgba(136,85,170,0.6)",
    liquidColorEnd: "rgba(136,85,170,0.3)",
    solidColor: "#8855aa",
    solidColorEnd: "#663388",
    solidType: "chunk",
  },
  {
    id: "metyl_da",
    name: "Metyl Da Cam",
    formula: "C₁₄H₁₄N₃NaO₃S",
    color: "#ff8800",
    concentration: "0.1%",
    category: "indicator",
    state: "aqueous",
    description: "Chất chỉ thị màu: đỏ trong axit, vàng trong bazơ",
    molarMass: 327.33,
    liquidColor: "rgba(255,136,0,0.7)",
    liquidColorEnd: "rgba(255,180,50,0.5)",
  },

  // ─── Metals ───
  {
    id: "zn",
    name: "Kẽm",
    formula: "Zn",
    color: "#a0b0c0",
    category: "metal",
    state: "solid",
    description: "Kim loại màu xám bạc, phản ứng với axit tạo H₂",
    molarMass: 65.38,
    liquidColor: "rgba(160,176,192,0.7)",
    liquidColorEnd: "rgba(160,176,192,0.3)",
    solidColor: "#b0c0d0",
    solidColorEnd: "#8090a0",
    solidType: "metal",
  },
  {
    id: "fe",
    name: "Sắt",
    formula: "Fe",
    color: "#887766",
    category: "metal",
    state: "solid",
    description: "Kim loại màu xám, phản ứng với axit tạo H₂",
    molarMass: 55.85,
    liquidColor: "rgba(136,119,102,0.7)",
    liquidColorEnd: "rgba(136,119,102,0.3)",
    solidColor: "#a09080",
    solidColorEnd: "#706050",
    solidType: "metal",
  },
  {
    id: "cu",
    name: "Đồng",
    formula: "Cu",
    color: "#cc8833",
    category: "metal",
    state: "solid",
    description: "Kim loại màu đỏ cam, dẫn điện tốt",
    molarMass: 63.55,
    liquidColor: "rgba(204,136,51,0.7)",
    liquidColorEnd: "rgba(204,136,51,0.3)",
    solidColor: "#dd9944",
    solidColorEnd: "#bb6622",
    solidType: "metal",
  },
  {
    id: "mg",
    name: "Magie",
    formula: "Mg",
    color: "#dddddd",
    category: "metal",
    state: "solid",
    description: "Kim loại nhẹ, màu trắng bạc, cháy sáng",
    molarMass: 24.31,
    liquidColor: "rgba(220,220,230,0.8)",
    liquidColorEnd: "rgba(200,200,210,0.4)",
    solidColor: "#e0e0e8",
    solidColorEnd: "#c0c0c8",
    solidType: "metal",
    flammable: true,
  },
  {
    id: "al",
    name: "Nhôm",
    formula: "Al",
    color: "#c0c8d0",
    category: "metal",
    state: "solid",
    description: "Kim loại nhẹ, màu trắng bạc",
    molarMass: 26.98,
    liquidColor: "rgba(192,200,208,0.7)",
    liquidColorEnd: "rgba(192,200,208,0.3)",
    solidColor: "#d0d8e0",
    solidColorEnd: "#a0b0c0",
    solidType: "metal",
  },
  {
    id: "ag",
    name: "Bạc",
    formula: "Ag",
    color: "#e0e0e0",
    category: "metal",
    state: "solid",
    description: "Kim loại màu trắng xám, tinh thể sáng",
    molarMass: 107.87,
    liquidColor: "rgba(224,224,224,0.7)",
    liquidColorEnd: "rgba(224,224,224,0.3)",
    solidColor: "#ececec",
    solidColorEnd: "#b8b8c0",
    solidType: "metal",
  },

  // ─── Salts ───
  {
    id: "nacl",
    name: "Natri Clorua",
    formula: "NaCl",
    color: "#ffffff",
    category: "salt",
    state: "solid",
    description: "Muối ăn, tinh thể trắng",
    molarMass: 58.44,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(245,248,255,0.85)",
    solidColor: "#f8faff",
    solidColorEnd: "#d0d8e8",
    solidType: "crystal",
  },
  {
    id: "cuso4",
    name: "Đồng(II) Sunfat",
    formula: "CuSO₄",
    color: "#4488ff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch màu xanh lam đặc trưng",
    molarMass: 159.61,
    liquidColor: "rgba(30,100,220,0.85)",
    liquidColorEnd: "rgba(50,140,255,0.7)",
    toxic: true,
  },
  {
    id: "feso4",
    name: "Sắt(II) Sunfat",
    formula: "FeSO₄",
    color: "#66bb88",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch màu xanh lục nhạt",
    molarMass: 151.91,
    liquidColor: "rgba(60,180,120,0.8)",
    liquidColorEnd: "rgba(100,200,150,0.65)",
  },
  {
    id: "fecl3",
    name: "Sắt(III) Clorua",
    formula: "FeCl₃",
    color: "#cc7733",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch màu vàng nâu",
    molarMass: 162.2,
    liquidColor: "rgba(200,120,50,0.85)",
    liquidColorEnd: "rgba(180,100,40,0.7)",
    corrosive: true,
  },
  {
    id: "agno3",
    name: "Bạc Nitrat",
    formula: "AgNO₃",
    color: "#ffffff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu, nhạy sáng",
    molarMass: 169.87,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,245,255,0.85)",
    hazardous: true,
  },
  {
    id: "kmno4",
    name: "Kali Pemanganat",
    formula: "KMnO₄",
    color: "#aa2266",
    concentration: "0.02M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch màu tím đậm, chất oxi hóa mạnh",
    molarMass: 158.03,
    liquidColor: "rgba(140,30,80,0.85)",
    liquidColorEnd: "rgba(180,50,120,0.65)",
    hazardous: true,
  },
  {
    id: "na2co3",
    name: "Natri Cacbonat",
    formula: "Na₂CO₃",
    color: "#ffffff",
    concentration: "0.5M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu, có tính bazơ yếu, là muối cacbonat",
    molarMass: 105.99,
    carbonate: true,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(235,248,255,0.85)",
  },
  {
    id: "bacl2",
    name: "Bari Clorua",
    formula: "BaCl₂",
    color: "#ffffff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu, nhận biết ion sunfat",
    molarMass: 208.23,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,245,250,0.85)",
    toxic: true,
  },
  {
    id: "pbno32",
    name: "Chì(II) Nitrat",
    formula: "Pb(NO₃)₂",
    color: "#ffffff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu, rất độc",
    molarMass: 331.21,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,245,250,0.85)",
    toxic: true,
  },
  {
    id: "ki",
    name: "Kali Iodua",
    formula: "KI",
    color: "#ffffff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu",
    molarMass: 166.0,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(245,248,255,0.85)",
  },
  {
    id: "na2so4",
    name: "Natri Sunfat",
    formula: "Na₂SO₄",
    color: "#ffffff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu, chứa ion sunfat",
    molarMass: 142.04,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,248,255,0.85)",
  },
  {
    id: "cu_no32",
    name: "Đồng(II) Nitrat",
    formula: "Cu(NO₃)₂",
    color: "#4488ff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch màu xanh lam",
    molarMass: 187.56,
    liquidColor: "rgba(30,100,220,0.85)",
    liquidColorEnd: "rgba(60,140,255,0.7)",
  },
  {
    id: "kscn",
    name: "Kali Thioxyanat",
    formula: "KSCN",
    color: "#ffffff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu, nhận biết ion Fe³⁺ (tạo màu đỏ máu)",
    molarMass: 97.18,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(245,248,255,0.85)",
  },
  {
    id: "caco3",
    name: "Canxi Cacbonat",
    formula: "CaCO₃",
    color: "#ffffff",
    category: "salt",
    state: "solid",
    description: "Chất rắn màu trắng, không tan, là muối cacbonat",
    molarMass: 100.09,
    carbonate: true,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,240,245,0.85)",
    solidColor: "#f0f0f5",
    solidColorEnd: "#d8dce6",
    solidType: "powder",
  },
  {
    id: "cuoh2",
    name: "Đồng(II) Hidroxit",
    formula: "Cu(OH)₂",
    color: "#4488cc",
    category: "salt",
    state: "solid",
    description: "Kết tủa màu xanh lam, không tan trong nước",
    molarMass: 97.56,
    liquidColor: "rgba(68,136,204,0.7)",
    liquidColorEnd: "rgba(68,136,204,0.4)",
    solidColor: "#5a9bd6",
    solidColorEnd: "#3a6fa8",
    solidType: "powder",
  },
  {
    id: "feoh3",
    name: "Sắt(III) Hidroxit",
    formula: "Fe(OH)₃",
    color: "#b5532a",
    category: "salt",
    state: "solid",
    description: "Kết tủa màu nâu đỏ, không tan trong nước",
    molarMass: 106.87,
    liquidColor: "rgba(181,83,42,0.7)",
    liquidColorEnd: "rgba(181,83,42,0.4)",
    solidColor: "#c9703f",
    solidColorEnd: "#8f3d1c",
    solidType: "powder",
  },
  {
    id: "agcl",
    name: "Bạc Clorua",
    formula: "AgCl",
    color: "#f0f0f0",
    category: "salt",
    state: "solid",
    description: "Kết tủa màu trắng, không tan trong nước, hóa đen ngoài ánh sáng",
    molarMass: 143.32,
    liquidColor: "rgba(240,240,240,0.7)",
    liquidColorEnd: "rgba(240,240,240,0.4)",
    solidColor: "#f5f5f8",
    solidColorEnd: "#c8c8d0",
    solidType: "powder",
  },
  {
    id: "baso4",
    name: "Bari Sunfat",
    formula: "BaSO₄",
    color: "#f5f5f5",
    category: "salt",
    state: "solid",
    description: "Kết tủa màu trắng, không tan trong axit",
    molarMass: 233.39,
    liquidColor: "rgba(245,245,245,0.7)",
    liquidColorEnd: "rgba(245,245,245,0.4)",
    solidColor: "#fafafa",
    solidColorEnd: "#d0d0d8",
    solidType: "powder",
  },
  {
    id: "pbi2",
    name: "Chì(II) Iodua",
    formula: "PbI₂",
    color: "#ffd700",
    category: "salt",
    state: "solid",
    description: "Kết tủa màu vàng tươi, ít tan trong nước lạnh",
    molarMass: 461.01,
    liquidColor: "rgba(255,215,0,0.7)",
    liquidColorEnd: "rgba(255,215,0,0.4)",
    solidColor: "#ffe14d",
    solidColorEnd: "#d4af00",
    solidType: "powder",
    hazardous: true,
  },
  {
    id: "fe2so43",
    name: "Sắt(III) Sunfat",
    formula: "Fe₂(SO₄)₃",
    color: "#b98a4a",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch màu vàng nâu nhạt",
    molarMass: 399.88,
    liquidColor: "rgba(185,138,74,0.8)",
    liquidColorEnd: "rgba(200,155,95,0.65)",
  },
  {
    id: "ch3coona",
    name: "Natri Axetat",
    formula: "CH₃COONa",
    color: "#ffffff",
    concentration: "1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu, muối của axit axetic",
    molarMass: 82.03,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(245,250,240,0.85)",
  },
  {
    id: "nh4cl",
    name: "Amoni Clorua",
    formula: "NH₄Cl",
    color: "#ffffff",
    concentration: "0.5M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu, tạo khói trắng với NH₃",
    molarMass: 53.49,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,248,250,0.85)",
  },
  {
    id: "zncl2",
    name: "Kẽm Clorua",
    formula: "ZnCl₂",
    color: "#ffffff",
    concentration: "0.5M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu",
    molarMass: 136.3,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,248,250,0.85)",
  },
  {
    id: "mgcl2",
    name: "Magie Clorua",
    formula: "MgCl₂",
    color: "#ffffff",
    concentration: "0.5M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu",
    molarMass: 95.21,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,248,250,0.85)",
  },
  {
    id: "alcl3",
    name: "Nhôm Clorua",
    formula: "AlCl₃",
    color: "#ffffff",
    concentration: "0.5M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu",
    molarMass: 133.34,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,248,250,0.85)",
  },
  {
    id: "fecl2",
    name: "Sắt(II) Clorua",
    formula: "FeCl₂",
    color: "#66ccaa",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch màu xanh lục nhạt",
    molarMass: 126.75,
    liquidColor: "rgba(60,180,140,0.8)",
    liquidColorEnd: "rgba(100,200,170,0.65)",
  },
  {
    id: "cacl2",
    name: "Canxi Clorua",
    formula: "CaCl₂",
    color: "#ffffff",
    concentration: "0.5M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu",
    molarMass: 110.98,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,248,250,0.85)",
  },
  {
    id: "kclo3",
    name: "Kali Clorat",
    formula: "KClO₃",
    color: "#ffffff",
    category: "salt",
    state: "solid",
    description: "Tinh thể trắng, đun nóng với MnO₂ giải phóng O₂",
    molarMass: 122.55,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,248,250,0.85)",
    solidColor: "#f8faff",
    solidColorEnd: "#d8e0ec",
    solidType: "crystal",
    hazardous: true,
  },
  {
    id: "i2",
    name: "Iot",
    formula: "I₂",
    color: "#5b2c6f",
    category: "other",
    state: "solid",
    description: "Tinh thể tím đen, thăng hoa khi đun nóng, nhận biết tinh bột",
    molarMass: 253.81,
    liquidColor: "rgba(120,60,150,0.7)",
    liquidColorEnd: "rgba(120,60,150,0.4)",
    solidColor: "#6b3480",
    solidColorEnd: "#47205a",
    solidType: "crystal",
    toxic: true,
  },
  {
    id: "tinh_bot",
    name: "Tinh Bột",
    formula: "(C₆H₁₀O₅)ₙ",
    color: "#fdfdfd",
    category: "other",
    state: "solid",
    description: "Bột trắng, tạo màu xanh tím với iot",
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(245,245,245,0.85)",
    solidColor: "#fdfdfd",
    solidColorEnd: "#e0e0e0",
    solidType: "powder",
  },
  {
    id: "mno2",
    name: "Mangan Đioxit",
    formula: "MnO₂",
    color: "#333333",
    category: "other",
    state: "solid",
    description: "Bột màu đen, xúc tác phân hủy H₂O₂ và KClO₃",
    molarMass: 86.94,
    liquidColor: "rgba(60,60,60,0.7)",
    liquidColorEnd: "rgba(60,60,60,0.4)",
    solidColor: "#444444",
    solidColorEnd: "#202020",
    solidType: "powder",
  },
  {
    id: "h2o2",
    name: "Hidro Peroxit",
    formula: "H₂O₂",
    color: "#ffffff",
    concentration: "3%",
    category: "other",
    state: "aqueous",
    description: "Dung dịch không màu, phân hủy tạo O₂ khi có xúc tác MnO₂",
    molarMass: 34.01,
    liquidColor: "rgba(255,255,255,0.92)",
    liquidColorEnd: "rgba(240,250,250,0.85)",
    hazardous: true,
  },
  {
    id: "cao",
    name: "Canxi Oxit",
    formula: "CaO",
    color: "#f0f0f0",
    category: "other",
    state: "solid",
    description: "Chất rắn màu trắng (vôi sống), tạo ra khi nhiệt phân CaCO₃",
    molarMass: 56.08,
    liquidColor: "rgba(240,240,240,0.7)",
    liquidColorEnd: "rgba(240,240,240,0.4)",
    solidColor: "#f5f5f5",
    solidColorEnd: "#d8d8dc",
    solidType: "powder",
  },
  {
    id: "mgo",
    name: "Magie Oxit",
    formula: "MgO",
    color: "#f5f5f5",
    category: "other",
    state: "solid",
    description: "Chất rắn màu trắng, tạo ra khi magie cháy trong oxi",
    molarMass: 40.3,
    liquidColor: "rgba(245,245,245,0.7)",
    liquidColorEnd: "rgba(245,245,245,0.4)",
    solidColor: "#fafafa",
    solidColorEnd: "#dcdcdc",
    solidType: "powder",
  },
  {
    id: "nano3",
    name: "Natri Nitrat",
    formula: "NaNO₃",
    color: "#ffffff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu",
    molarMass: 84.99,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(245,248,255,0.85)",
  },
  {
    id: "kno3",
    name: "Kali Nitrat",
    formula: "KNO₃",
    color: "#ffffff",
    concentration: "0.2M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu",
    molarMass: 101.1,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(245,248,255,0.85)",
  },
  {
    id: "kcl",
    name: "Kali Clorua",
    formula: "KCl",
    color: "#ffffff",
    concentration: "0.5M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu",
    molarMass: 74.55,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(245,248,255,0.85)",
  },
  {
    id: "k2so4",
    name: "Kali Sunfat",
    formula: "K₂SO₄",
    color: "#ffffff",
    concentration: "0.05M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu",
    molarMass: 174.26,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(245,248,255,0.85)",
  },
  {
    id: "mnso4",
    name: "Mangan(II) Sunfat",
    formula: "MnSO₄",
    color: "#eeccee",
    concentration: "0.05M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch hồng nhạt",
    molarMass: 151.0,
    liquidColor: "rgba(238,204,238,0.85)",
    liquidColorEnd: "rgba(230,190,230,0.7)",
  },
  {
    id: "znso4",
    name: "Kẽm Sunfat",
    formula: "ZnSO₄",
    color: "#ffffff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu",
    molarMass: 161.47,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,248,250,0.85)",
  },
  {
    id: "baco3",
    name: "Bari Cacbonat",
    formula: "BaCO₃",
    color: "#f5f5f5",
    category: "salt",
    state: "solid",
    description: "Kết tủa trắng, là muối cacbonat không tan",
    molarMass: 197.34,
    carbonate: true,
    liquidColor: "rgba(245,245,245,0.7)",
    liquidColorEnd: "rgba(245,245,245,0.4)",
    solidColor: "#fafafa",
    solidColorEnd: "#d8d8e0",
    solidType: "powder",
  },
  {
    id: "ba_no32",
    name: "Bari Nitrat",
    formula: "Ba(NO₃)₂",
    color: "#ffffff",
    concentration: "0.1M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu",
    molarMass: 261.34,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(245,248,255,0.85)",
  },
  {
    id: "ba_ch3coo2",
    name: "Bari Axetat",
    formula: "(CH₃COO)₂Ba",
    color: "#ffffff",
    concentration: "0.5M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu, muối của axit axetic",
    molarMass: 255.42,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(245,250,240,0.85)",
  },
  {
    id: "ca_no32",
    name: "Canxi Nitrat",
    formula: "Ca(NO₃)₂",
    color: "#ffffff",
    concentration: "0.5M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu",
    molarMass: 164.09,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(240,248,250,0.85)",
  },
  {
    id: "caso4",
    name: "Canxi Sunfat",
    formula: "CaSO₄",
    color: "#f5f5f5",
    category: "salt",
    state: "solid",
    description: "Chất rắn màu trắng, ít tan trong nước (thạch cao)",
    molarMass: 136.14,
    liquidColor: "rgba(245,245,245,0.7)",
    liquidColorEnd: "rgba(245,245,245,0.4)",
    solidColor: "#fafafa",
    solidColorEnd: "#d8dce0",
    solidType: "powder",
  },
  {
    id: "ca_ch3coo2",
    name: "Canxi Axetat",
    formula: "(CH₃COO)₂Ca",
    color: "#ffffff",
    concentration: "0.5M",
    category: "salt",
    state: "aqueous",
    description: "Dung dịch không màu, muối của axit axetic",
    molarMass: 158.17,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(245,250,240,0.85)",
  },
  {
    id: "fescn3",
    name: "Phức Sắt(III) Thioxyanat",
    formula: "[Fe(SCN)]²⁺",
    color: "#cc1111",
    concentration: "0.1M",
    category: "other",
    state: "aqueous",
    description: "Dung dịch phức màu đỏ máu, dùng nhận biết ion Fe³⁺",
    molarMass: 170.03,
    liquidColor: "rgba(200,20,20,0.85)",
    liquidColorEnd: "rgba(220,60,60,0.7)",
  },

  // ─── Organic ───
  {
    id: "etanol",
    name: "Etanol",
    formula: "C₂H₅OH",
    color: "#ffffff",
    concentration: "96%",
    category: "organic",
    state: "liquid",
    description: "Rượu etylic, không màu, dễ cháy",
    molarMass: 46.07,
    liquidColor: "rgba(255,255,255,0.92)",
    liquidColorEnd: "rgba(240,248,255,0.85)",
    flammable: true,
  },
  {
    id: "glucose",
    name: "Glucose",
    formula: "C₆H₁₂O₆",
    color: "#ffffff",
    concentration: "0.5M",
    category: "organic",
    state: "aqueous",
    description: "Dung dịch đường, không màu",
    molarMass: 180.16,
    liquidColor: "rgba(255,255,255,0.9)",
    liquidColorEnd: "rgba(248,248,240,0.85)",
  },

  // ─── Gases ───
  {
    id: "co2",
    name: "Khí Cacbonic",
    formula: "CO₂",
    color: "#ffffff",
    category: "gas",
    state: "gas",
    description: "Khí không màu, làm đục nước vôi trong",
    molarMass: 44.01,
    liquidColor: "rgba(255,255,255,0.5)",
    liquidColorEnd: "rgba(255,255,255,0.3)",
  },
  {
    id: "o2",
    name: "Khí Oxi",
    formula: "O₂",
    color: "#ffffff",
    category: "gas",
    state: "gas",
    description: "Khí không màu, duy trì sự cháy",
    molarMass: 32.0,
    liquidColor: "rgba(255,255,255,0.5)",
    liquidColorEnd: "rgba(255,255,255,0.3)",
  },
];

// Nhóm hóa chất theo category — không dùng emoji, dùng chữ cái/SVG
export const chemicalCategories = [
  { id: "all", name: "Tất cả" },
  { id: "acid", name: "Axit" },
  { id: "base", name: "Bazơ" },
  { id: "indicator", name: "Chất chỉ thị" },
  { id: "metal", name: "Kim loại" },
  { id: "salt", name: "Muối" },
  { id: "organic", name: "Hữu cơ" },
  { id: "gas", name: "Khí" },
  { id: "other", name: "Khác" },
] as const;

export function getChemicalById(id: string): Chemical | undefined {
  return chemicals.find((c) => c.id === id);
}

// Lấy màu gradient của dung dịch
export function getLiquidGradient(chemical: Chemical): string {
  const end = chemical.liquidColorEnd || chemical.liquidColor;
  return `linear-gradient(180deg, ${chemical.liquidColor}, ${end})`;
}

// Lấy màu gradient cho chất rắn
export function getSolidGradient(chemical: Chemical): string {
  const end = chemical.solidColorEnd || chemical.solidColor || chemical.color;
  const start = chemical.solidColor || chemical.color;
  return `linear-gradient(135deg, ${start}, ${end})`;
}

// Kiểm tra có phải chất lỏng/dung dịch không
export function isLiquidState(state: string): boolean {
  return state === "liquid" || state === "aqueous";
}

// Lấy nhãn viết tắt cho trạng thái
export function getStateLabel(state: string): string {
  switch (state) {
    case "aqueous": return "dd";
    case "liquid": return "l";
    case "solid": return "r";
    case "gas": return "k";
    default: return "";
  }
}
